name: UnitTests

on:
  pull_request:
    types: [opened, reopened]
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore Gameserver dependencies
        run: dotnet restore ./Gameserver/Gameserver

      - name: Gameserver build
        run: dotnet build ./Gameserver/Gameserver --no-restore /p:ContinuousIntegrationBuild=true
      
      - name: Gameserver test
        run: dotnet test ./Gameserver/Gameserver /p:CollectCoverage=true /p:CoverletOutput=TestResult/ /p:CoverletOutputFormat=cobertura
        
      - name: Checkstyle
        run: dotnet format ./Gameserver/Gameserver.sln --verify-no-changes